## Load and Compute

In [ ]:
from metrics import ADI
import numpy as np
import pandas as pd
from project_consts import DATASET_DIR, EMBEDDINGS_DIR, RESULTS_DIR
from tqdm import tqdm
import json

In [ ]:
with open(RESULTS_DIR / "cluster_res.json", 'r') as f:
    data = json.load(f)

In [ ]:
cadi_scores = {
    dataset: {
        alg: alg_data['CADI']
        for alg, alg_data in
        ds_data.items()
    }
    for dataset, ds_data
    in data.items()
}

In [ ]:
cadi_df = pd.DataFrame(cadi_scores).T

In [ ]:
seed = 100

scores = dict()

dsfiles = list(DATASET_DIR.iterdir())
for dsfile in tqdm(dsfiles, position=0):
    dataset_name = dsfile.stem
    X = np.load(dsfile)
    embs = {
        embfile.stem : np.load(embfile)
        for embfile in (EMBEDDINGS_DIR / dataset_name).iterdir()
    }

    scores[dataset_name] = {embname: ADI(X, Y, X.shape[0] * 100, random_seed=100) for embname, Y in tqdm(embs.items(), desc=dataset_name, position=1, leave=False)}

100%|██████████| 19/19 [04:29<00:00, 14.19s/it]

In [ ]:
adi_df = pd.DataFrame(scores).T

In [ ]:
adi_df.style.background_gradient(axis=1, cmap='PuBu_r')

## CADI vs ADI

In [ ]:
corr_df = adi_df.corrwith(cadi_df, axis=1, method='pearson')

In [ ]:
corr_df

MNIST           0.072793
acl_imdb        0.583305
coil100         0.517594
coil20          0.557672
concentric3     0.979592
concentric4     0.991507
donuts          0.991830
emotion        -0.741660
fashionMNIST    0.780169
liver           0.740279
matryoshka      0.914035
olivetti        0.697094
pbmc3k         -0.765146
pendigits       0.913457
penguins        0.616402
rings           0.778213
sentiment       0.792202
trec           -0.209359
usps            0.568312
dtype: float64

## ADI is global

In [ ]:
sorted_idx = np.argsort(adi_df.to_numpy(), axis=1)

bests = pd.DataFrame({
    'Rank 1': adi_df.columns[sorted_idx[:, 0]],
    'Rank 2': adi_df.columns[sorted_idx[:, 1]]
}, index=adi_df.index)

bests

                      Rank 1          Rank 2
MNIST                    MDS            TSNE
acl_imdb                 MDS  AngleEmbedding
coil100                  MDS             PCA
coil20                   MDS             PCA
concentric3   AngleEmbedding             MDS
concentric4   AngleEmbedding             PCA
donuts                   MDS             PCA
emotion                  MDS           UMATO
fashionMNIST             MDS             PCA
liver                    MDS  AngleEmbedding
matryoshka    AngleEmbedding             MDS
olivetti                 MDS             PCA
pbmc3k                   MDS          Random
pendigits                MDS             PCA
penguins                 PCA             MDS
rings         AngleEmbedding             MDS
sentiment     AngleEmbedding             MDS
trec                     MDS            TSNE
usps                     MDS             PCA

In [ ]:
(bests == 'MDS').sum()

Rank 1    13
Rank 2     5
dtype: int64

In [ ]:
(bests == 'PCA').sum()

Rank 1    1
Rank 2    8
dtype: int64

### CADI bests

In [ ]:
sorted_idx = np.argsort(cadi_df.to_numpy(), axis=1)

cadi_bests = pd.DataFrame({
    'Best': cadi_df.columns[sorted_idx[:, 0]],
    '2nd Best': cadi_df.columns[sorted_idx[:, 1]]
}, index=cadi_df.index)

cadi_bests

                        Best        2nd Best
usps          AngleEmbedding            TSNE
trec          AngleEmbedding             PCA
sentiment     AngleEmbedding             MDS
rings         AngleEmbedding             MDS
penguins      AngleEmbedding            TSNE
pendigits     AngleEmbedding           UMATO
pbmc3k        AngleEmbedding            TSNE
olivetti      AngleEmbedding            UMAP
matryoshka    AngleEmbedding             PCA
liver         AngleEmbedding             PCA
fashionMNIST  AngleEmbedding            TSNE
emotion       AngleEmbedding           UMATO
donuts                   MDS  AngleEmbedding
concentric4   AngleEmbedding             PCA
concentric3   AngleEmbedding             MDS
coil20        AngleEmbedding            TSNE
coil100       AngleEmbedding            TSNE
acl_imdb      AngleEmbedding             MDS
MNIST         AngleEmbedding            TSNE

In [ ]:
(cadi_bests == 'MDS').sum()

Best        1
2nd Best    4
dtype: int64

In [ ]:
(cadi_bests == 'PCA').sum()

Best        0
2nd Best    4
dtype: int64